# Generated by Django 3.2.6 on 2021-08-13 02:59

from django.db import migrations, models
import match.storage


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0002_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='owlFile',
            field=models.FileField(storage=match.storage.OverwriteStorage(), upload_to='uploaded_ontologies/'),
        ),
    ]
